### ISSUE TITLE
winrepo.genrepo reports exception when using jinja in init.sls 

### ISSUE THREAD

**Issue by billcchung** [saltstack/salt-winrepo#57] opened 2014-07-01 02:56 UTC
Hi Guys,

I keep getting an exception while applying jinja in init.sls.
The init.sls (/srv/salt/repo/win/splunk/init.sls):
````yaml
#! yaml_jinja

splunk:
  {% for pkg in ['5.0.6-185900-x64', '5.0.7-192045-x64', '6.0.1-187445-x64'] %}
  {{ pkg }}:
    installer: salt://repo/win/splunk/splunk-{{ pkg }}-release.msi
    full_name: splunk-{{ pkg }}
    reboot: False
    install_flags: 'AGREETOLICENSE=Yes /quiet'
    msiexec: True
    uninstaller: salt://repo/win/splunk/splunk-{{ pkg }}-release.msi
    uninstall_flags: '/quiet'
  {% endfor %}
````

but i kept getting an excpetion while running "salt-run winrepo.genrepo"
````python
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 95, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 362, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 218, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 125, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/winrepo.py", line 46, in genrepo
    config = yaml.safe_load(slsfile.read()) or {}
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "<string>", line 4, column 4:
      {% for pkg in ['5.0.6-185900-x64' ...
````

It seems like the file was not going through jinja, I tried uncommenting the line:
````python
renderer: yaml_jinja
````
in /etc/salt/master, to make sure it's using yaml_jinja.
win_repo is set to  '/srv/salt/repo/win' on purpose (This should not cause the issue, just clearing what I did.)
other settings were left by defaults.

Both salt-master and minion are running at 2014.1.5 

I might be missing some settings or misconfiguring the settings, but I couldnt find where. 
Could someone help me out? 
Thanks in advance.
-bill

**Comment by eliasp** [comment] 2015-01-08 00:46
@UtahDave I think this one can be closed as a duplicate of #6859

**Comment by twangboy** [comment] 2015-07-07 23:14
Fixed by #24980
Will be available in 2015.8 (Beryllium)

**Closed by twangboy** 2015-07-07 23:14 UTC

**Comment by TheBigBear** [comment] 2015-07-11 08:56
@twangboy this is great. So this means jinja support is coming to winrepo sls files, right? 
If so, how can I tell a winrepo sls file that it needs version >= 2015.8.x, so it can process jinja in it?
I would really like to cleanup/improve the winrepo sls files and switch to files that use jinja to determine if they need to install the x64/amd 64-bit installer or the x86 32-bit one for a starter. 
And there is a numbr of scenarios that can now be handled more elegantly or gracefully with jinja support at the ready. 
But without being able to require a version number of the salt minion of >= 2015.8.x in the actual winrepo slsl file, I can't put any jinja into the winrepo sls files? And how long would one have to wait until 'everybody' is on at least >= 2015.8?
Is this already solved? Or should I create an issue for it?
ping @UtahDave

**Comment by twangboy** [comment] 2015-07-13 17:13
@TheBigBear @UtahDave 
As I understand it, we'll have to use a separate repo for Salt-Minion 2015.8. Jinja in the .sls definitions will break winrepo on older versions on Salt. There's really no clean way to make the transition.

**Comment by TheBigBear** [comment] 2015-07-13 18:01
@twangboy @UtahDave, hmmhh, that is kind of what I was expecting. ;-( Luckily I have NO older minions on my networks. ;-) 
@UtahDave could this be the time to add/expand the functionality of winrepo, to deal with some of the biggest frustrations or limitiations? Or is that 'too late' to have any hope to make it into 2015.8 (Beryllium)?
